### ISSUE TITLE
Linking error?

### ISSUE THREAD

**Issue by TalDerei** [ingonyama-zk/icicle#10]
I'm getting a linking error when trying run "Cargo test", resulting in **"could not compile `icicle-utils` due to previous error; 15 warnings emitted"** and **"error: linking with `cc` failed: exit status: 1"** errors. Building the ICICLE library using nvcc and running "cargo build --release" works, but the tests fail for some reason. 

In the error logs, it's mentioning that **"= note: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified".** Running only the MSM tests produce the same errors for example. 

I've built the codebase by setting -arch=native (to autodetect the GPU), and arch=compute_80 (for the Ampere A10). Both builds produce the same error. I'm running on Linux Ubuntu 22.04 distribution. 

Any insight into what's going on would be appreciated!

**Comment by omershlo** [comment]
@TalDerei thanks for reporting and for testing the code. We are looking into this and will update asap

**Comment by TalDerei** [comment]
I just saw there was another PR#9 opened this morning for fixing build errors. Not sure if this is a related issue.

**Comment by robik75** [comment]
> I just saw there was another PR#9 opened this morning for fixing build errors. Not sure if this is a related issue.

yes, #9 should fix the linking errors

**Comment by LeonHibnik** [comment]
Closed in #9.

**Comment by LeonHibnik** [comment]
Closed in #9.
