### ISSUE TITLE
[BUG]: CUDA test suite fails

### ISSUE THREAD

**Issue by jeremyfelder** [ingonyama-zk/icicle#103]
## Description

When running the CUDA test suite, the following error is encountered:

`icicle/icicle/primitives/test_kernels.cuh:4:10: fatal error: ../curves/bls12_381.cuh: No such file or directory`

### Reproduce

Follow the instructions for building and testing in the README

## Expected Behavior

The tests should run and pass

## Environment

Please complete the following information:

OS + Version:

Cargo Version:

GPU type:

**Comment by gkigiermo** [comment]
As commented on Discord, I will start working on this.
