### ISSUE TITLE
[FEAT]: Add error handling for asynchronous calls

### ISSUE THREAD

**Issue by jeremyfelder** [ingonyama-zk/icicle#109]
## Description

Add proper error handling on all asynchronous calls, as later calls may return previous calls' errors. See the first bullet points in the second Notes section here: https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__MEMORY__POOLS.html#group__CUDART__MEMORY__POOLS_1gbbf70065888d61853c047513baa14081

## Motivation

Proper error handling is necessary to report errors to the caller and/or to terminate early to prevent incorrect results

**Comment by DmytroTym** [comment]
Please reopen if I'm wrong but I think this is solved in v1.0.0 by checking for errors at the start of functions
