### ISSUE TITLE
[FEAT]: Merkle tree builder

### ISSUE THREAD

**Issue by ChickenLover** [ingonyama-zk/icicle#120]
## Description

A function to build large merkle trees on GPU. It should support any arity supported by our current poseidon impl. Implement subtree-splitting to make large trees computable on devices.

## Motivation

Merkle trees are a golden standard of tables commitments. ZK trace tables are huge. => We need large merkle trees on GPU

**Comment by DmytroTym** [comment]
Can this be closed @ChickenLover ?
