### ISSUE TITLE
Coordinate conversions

### ISSUE THREAD

**Issue by TalDerei** [ingonyama-zk/icicle#13]
Codebase implements conversion between affine and projective coordinates. I think it would be helpful to add helper methods to conversions between jacobian and projective coordinates as well.

**Comment by TalDerei** [comment]
It's low priority. But to give some motivation, there's a lot of older codebases that work with Jacobian coordinates (Mina, Barretenberg, etc.). Dwitching to projective coordinates will require checking newer outputs (in Projective coordinates) against an expected target in a different coordinate system (Jacobian coordinates).

**Comment by TalDerei** [comment]
@omershlo Is there a simple way to make this conversion? I've ported over your  I actually need this in my codebase: https://github.com/TalDerei/cuda-barretenberg/blob/msm/src/aztec/gpu/curves/group.cu#L209. I've ported over your projective addition algorithm, and I have a unit test with expected outputs in Jacobian form. 

I'm trying to verify the correctness of the algorithm. This is over the BN-254 curve.

**Comment by HadarIngonyama** [comment]
from projective to affine:
(x_p,y_p,z_p) -> (x_p/z_p,y_p/z_p)

then to jacobian:
(x_p/z_p,y_p/z_p,1)

**Comment by HadarIngonyama** [comment]
and the other direction, from jacobian to affine:
(x_j,y_j,z_j) -> (x_j/z_j^2,y_j/z_j^3)

then to projective:
(x_j/z_j^2,y_j/z_j^3,1)

**Comment by robik75** [comment]
@TalDerei you can go directly between jacobian and projective without going through affine and thus avoiding division.
The conversions are already implemented here:
- projective to jacobian https://github.com/matter-labs/era-bellman-cuda/blob/main/src/ec.cuh#L99-L104
- jacobian to projective https://github.com/matter-labs/era-bellman-cuda/blob/main/src/ec.cuh#L175-L180

**Comment by DmytroTym** [comment]
Btw, we do have projective-Jacobian conversions as part our arkworks conversions: https://github.com/ingonyama-zk/icicle/blob/main/wrappers/rust/icicle-core/src/curve.rs#L168
But it's exclusively on the Rust side and we still don't support Jacobian in ICICLE (tbh I don't know of any good reasons to do so), so I feel like it's not enough to close this
