### ISSUE TITLE
[BUG]:  Curve generation script not working

### ISSUE THREAD

**Issue by ImmanuelSegol** [ingonyama-zk/icicle#141]
## Description

Please provide a clear and concise description of the bug.

### Reproduce

Please list the steps to reproduce the issue.

## Expected Behavior

Please provide a clear and concise description of what you expected to happen.

## Environment

Please complete the following information:

OS + Version:

Cargo Version:

GPU type:

## Additional context

Please provide any additional context that may be helpful in confirming and resolving this issue.

**Comment by DmytroTym** [comment]
We made quite a bit of changes to the script in recent times, did in solve the issue @ImmanuelSegol? Does this being in Done mean it can be closed?
