### ISSUE TITLE
[FEAT]: Add bulk point and scalar generation methods

### ISSUE THREAD

**Issue by ImmanuelSegol** [ingonyama-zk/icicle#160]
## Description

Currently, in PRs like #158, we add a support function that can generate individual points/scalars on host memory.

We should expose bulk generate functions on device memory to speed up point generation.

**Comment by DmytroTym** [comment]
See [here](https://github.com/ingonyama-zk/icicle/blob/main/icicle/primitives/field.cu#L6) and [here](https://github.com/ingonyama-zk/icicle/blob/main/icicle/primitives/projective.cu#L20), Rust wrappers are also provided.
