### ISSUE TITLE
[BUG]: Broken links in the readme

### ISSUE THREAD

**Issue by weijiekoh** [ingonyama-zk/icicle#164]
## Description

[README.md](https://github.com/ingonyama-zk/icicle/blob/main/README.md) states:

```md
1. Define or select a curve for your application; we've provided a [template](https://github.com/ingonyama-zk/icicle/blob/main/icicle/curves/curve_template.cuh) for defining a curve
2. Include the curve in [curve_config.cuh](https://github.com/ingonyama-zk/icicle/blob/main/icicle/curves/curve_config.cuh)
```

It seems that the links to `curve_template.cuh` and `curve_config.cuh` no longer work.

Should the link to the curve template be to this directory instead? `https://github.com/ingonyama-zk/icicle/tree/main/icicle/curves/curve_template/`

Should the curve config file instead be `https://github.com/ingonyama-zk/icicle/blob/main/icicle/curves/index.cu`?

Thank you!

**Comment by jeremyfelder** [comment]
@weijiekoh Thanks for opening the issue! Yes, both of those links are outdated and those are the correct replacement links.
