### ISSUE TITLE
[BUG]: Infinity/zero points not filtered out

### ISSUE THREAD

**Issue by jeremyfelder** [ingonyama-zk/icicle#169]
## Description

When running MSMs that include infinity/zero points, an error occurs and the resulting point is a zero point

### Reproduce

Run msm with at least one point being a zero/infinity point

## Expected Behavior

Zero points should be filtered out and a correct result should be returned

**Comment by DmytroTym** [comment]
Just to comment on this one: the only protocol where I've seen zero points is Groth16, I don't think SRS-based schemes might have zero points in their MSMs. And in gnark's Groth16 zero points are filtered on CPU, right? I think that's the reason why we haven't implemented this yet, though I'm also not sure what's the best way to do this on GPU

**Comment by omershlo** [comment]
Lurk-labs told us that they have this problem as well (many zero points) in Nova.
cc: @krakhit @ChickenLover

**Comment by krakhit** [comment]
@omershlo : If I remember correctly he meant zero scalars, it affects the distribution from being uniform. I believe ICICLE algorithms already takes this into account. Zero points are not generally present in SRS based protocols. 

@jeremyfelder You encountered zero scalars in ezkl right?

**Comment by DmytroTym** [comment]
@krakhit yea we do have efficient handling of zero scalars in our MSM

**Comment by jeremyfelder** [comment]
Closing, completed in #372
