### ISSUE TITLE
MSM sum reduction optimization

### ISSUE THREAD

**Issue by TalDerei** [ingonyama-zk/icicle#17]
The **sum_reduction** kernel for short MSM implements sequential addressing for contigious memory access to avoid shared memory bank conflicts. This performs better than naive warp divergence (generally ~2x faster), but there are other optimizations that can be made, and applied to the **final_accumulation_kernel** for the large MSM as well. 

For example, in the sum reduction kernel, half the threads are idle after the first pass in the loop. Optimizations 4 and 5 in the guide address below this by launching half the number of threads and packing more work per thread, along with loop unrolling the last warp calculation.

https://developer.download.nvidia.com/assets/cuda/files/reduction.pdf

Here's some example code below: https://github.com/TalDerei/cuda-barretenberg/blob/msm/src/aztec/gpu/benchmark/tests/msm/example_test.cu

**Comment by TalDerei** [comment]
I think it would be worth looking into "cooperative groups" for performing these kinds of operations using tiled partitions. This allows for finer granularity for synchronization between threads.

**Comment by omershlo** [comment]
awesome suggestions @TalDerei 
cc: @HadarIngonyama  who wrote this part

**Comment by TalDerei** [comment]
If I have time, I'll push a PR implementing these suggestions.

**Comment by HadarIngonyama** [comment]
Yes these optimizations are on my roadmap for this kernel along with using shared memory. If you can implement them that would be amazing:)
