### ISSUE TITLE
[FEAT]: Add benchmarks for ICICLE primitives

### ISSUE THREAD

**Issue by ChickenLover** [ingonyama-zk/icicle#19]
## Description

Add benchmarks for:

- MSM
- NTT
- ECNTT
- Scalar Vector Multiplication
- Point Vector Multiplication

## Motivation

Benchmarks allow measuring performance and comparing with CPU implementation

**Comment by TalDerei** [comment]
Interesting to compare how MSM stacks up against ZPrize reference implementation.

**Comment by TalDerei** [comment]
Can someone benchmark the MSM on 2^26 scalars and points, and share their results? I'm getting some mixed numbers.
