### ISSUE TITLE
[FEAT]: Create ICICLE <> Ark bindings 

### ISSUE THREAD

**Issue by ImmanuelSegol** [ingonyama-zk/icicle#192]
## Description

Please provide a clear and concise description of the feature you would like included.

## Motivation

Please provide a clear and concise description of the motivation for adding this feature.

**Comment by DmytroTym** [comment]
@ImmanuelSegol not sure about this issue, is it the same as point 2 in https://github.com/ingonyama-zk/icicle/issues/137?
