### ISSUE TITLE
[BUG]: insufficient dependencies 

### ISSUE THREAD

**Issue by maciejskorski** [ingonyama-zk/icicle#193]
## Description

I can't build tests although dependencies seem OK. 

### Reproduce

```bash
mkdir -p build
cmake -S . -B build
cmake --build build
cd build && ctest

[ 18%] Built target gtest
[ 36%] Built target gtest_main
[ 45%] Building CUDA object CMakeFiles/primitives_test.dir/primitives/test.cu.o
/usr/include/boost/multiprecision/cpp_int/serialize.hpp(49): error: function "boost::serialization::make_nvp(const char *, T &) [with T=bool]" returns incomplete type "const boost::serialization::nvp<bool>"
     ar & make_nvp("sign", s);
                  ^

/usr/include/boost/multiprecision/cpp_int/serialize.hpp(52): error: function "boost::serialization::make_nvp(const char *, T &) [with T=std::size_t]" returns incomplete type "const boost::serialization::nvp<std::size_t>"
     ar & make_nvp("byte-count", byte_count);
                  ^

/usr/include/boost/multiprecision/cpp_int/serialize.hpp(62): error: function "boost::serialization::make_nvp(const char *, T &) [with T=unsigned char]" returns incomplete type "const boost::serialization::nvp<unsigned char>"
           ar & make_nvp("byte", byte);
                        ^

3 errors detected in the compilation of "/home/icicle/icicle/primitives/test.cu".
make[2]: *** [CMakeFiles/primitives_test.dir/build.make:77: CMakeFiles/primitives_test.dir/primitives/test.cu.o] Error 2
make[1]: *** [CMakeFiles/Makefile2:137: CMakeFiles/primitives_test.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

## Expected Behavior

I would expect the compilation to go through. 

I think it would be nice to demonstrate on CI/CD that the code actually builds in a fresh environment.

## Environment

Please complete the following information:

OS + Version: Linux 4654ec4915e6 5.19.0-1025-aws #26~22.04.1-Ubuntu SMP Mon Apr 24 01:58:15 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

GPU type: Tesla V100-SXM2-16GB

CUDA Version (nvcc): Cuda compilation tools, release 12.2, V12.2.91

CMake Version: 3.27.5

**Comment by ImmanuelSegol** [comment]
@maciejskorski Thanks for reporting, I'm looking into this now.

I'm assuming you are running this on "main" branch.

**Comment by maciejskorski** [comment]
@ImmanuelSegol thanks for the promt reply. Yes, the main branch. And from within the NVIDIA Docker container supplying CUDA 12.x. I believe some c++ dependencies that are considered standard in your dev/prod environment may not be that standard on other images. Let me know if I can help in debugging.

**Comment by ImmanuelSegol** [comment]
> @ImmanuelSegol thanks for the promt reply. Yes, the main branch. And from within the NVIDIA Docker container supplying CUDA 12.x. I believe some c++ dependencies that are considered standard in your dev/prod environment may not be that standard on other images. Let me know if I can help in debugging.

Can you paste in here or link me to the docker container you are using, please?

**Comment by maciejskorski** [comment]
> Can you paste in here or link me to the docker container you are using, please?

```bash
docker run -d \
   -it \
   --name nvidia-cuda \
   --runtime=nvidia \
   --mount type=bind,source=$(pwd),target=/home \
   --privileged \
   nvidia/cuda:12.2.0-devel-ubuntu20.04
```
[12.2.0-devel-ubuntu20.04 from DockerHub](https://hub.docker.com/layers/nvidia/cuda/12.2.0-devel-ubuntu20.04/images/sha256-c1d07892979445e720a5cf1f5abe6a910f45c6d638bf9997d6a807924eee5190?context=explore)

**Comment by ImmanuelSegol** [comment]
@maciejskorski It should be fixed here #195

Thanks for opening this bug!

**Comment by ImmanuelSegol** [comment]
@maciejskorski hopefully this should be resolved now.

**Comment by maciejskorski** [comment]
> @maciejskorski hopefully this should be resolved now.

@ImmanuelSegol yes, removing incompatible tests and clarifying minimal requirements with Docker solves the problem. The test battery builds and runs. Thanks! 👍
