### ISSUE TITLE
[TEST] fmt.Print() prevents test from hanging

### ISSUE THREAD

**Issue by ImmanuelSegol** [ingonyama-zk/icicle#205]
https://github.com/ingonyama-zk/icicle/blob/08862134e85c0f23443c20e12a11fb2a4c077b2a/goicicle/templates/curves/g2_test.go.tmpl#L49

https://github.com/ingonyama-zk/icicle/blob/08862134e85c0f23443c20e12a11fb2a4c077b2a/goicicle/templates/msm/msm_test.go.tmpl#L225

Removing the fmt.Print will make test hang.

**Comment by DmytroTym** [comment]
This was probably due to division by zero hanging instead of returning zero or throwing. @jeremyfelder had the same issue in https://github.com/ingonyama-zk/icicle/pull/386 and it was solved by setting `1/0 := 0`
