### ISSUE TITLE
[FEAT] Generic conversion in rust wrapper

### ISSUE THREAD

**Issue by ImmanuelSegol** [ingonyama-zk/icicle#209]
Here area some examples:

- [ ] https://github.com/ingonyama-zk/icicle/blob/ef8beb8d0c7d481b8f3f3a47d48695889e4079b3/src/curves/bn254.rs#L198
- [ ] https://github.com/ingonyama-zk/icicle/blob/ef8beb8d0c7d481b8f3f3a47d48695889e4079b3/src/curves/bn254.rs#L262
- [ ] https://github.com/ingonyama-zk/icicle/blob/ef8beb8d0c7d481b8f3f3a47d48695889e4079b3/src/curves/bn254.rs#L129
- [ ] https://github.com/ingonyama-zk/icicle/blob/ef8beb8d0c7d481b8f3f3a47d48695889e4079b3/src/curves/bn254.rs#L123
- [ ] https://github.com/ingonyama-zk/icicle/blob/ef8beb8d0c7d481b8f3f3a47d48695889e4079b3/src/curves/bls12_381.rs#L168
- [ ] https://github.com/ingonyama-zk/icicle/blob/ef8beb8d0c7d481b8f3f3a47d48695889e4079b3/src/curves/bls12_381.rs#L242
- [ ] https://github.com/ingonyama-zk/icicle/blob/ef8beb8d0c7d481b8f3f3a47d48695889e4079b3/src/curves/bls12_381.rs#L173
- [ ] https://github.com/ingonyama-zk/icicle/blob/ef8beb8d0c7d481b8f3f3a47d48695889e4079b3/src/curves/bls12_381.rs#L305
- [ ] https://github.com/ingonyama-zk/icicle/blob/ef8beb8d0c7d481b8f3f3a47d48695889e4079b3/src/curves/bls12_377.rs#L287

In general tho these should be implemented in a generic way.

**Comment by jeremyfelder** [comment]
Doesn't this conflict with #137 with regards to moving arkworks to a different library and keeping icicle integration independent?

**Comment by ImmanuelSegol** [comment]
> Doesn't this conflict with #137 with regards to moving arkworks to a different library and keeping icicle integration independent?

Yeah but is part of a series of tasks relating to rust bindings, its just hard to bunch them under an epic.

**Comment by DmytroTym** [comment]
Conversion from and into limbs are done [using](https://github.com/ingonyama-zk/icicle/blob/v1.0.0/wrappers/rust/icicle-core/src/traits.rs#L18) `Repr` associated type in `FieldImpl` trait, ark conversion is [implemented](https://github.com/ingonyama-zk/icicle/blob/v1.0.0/wrappers/rust/icicle-core/src/traits.rs#L30) in `ArkConvertible` trait and conversions between affine and projective is done [by From and Into](https://github.com/ingonyama-zk/icicle/blob/v1.0.0/wrappers/rust/icicle-core/src/curve.rs#L76). All is generic over field or curve. I think it's good enough so closing, reopen if I'm wrong pls
