### ISSUE TITLE
[FEAT] Implement error codes

### ISSUE THREAD

**Issue by ImmanuelSegol** [ingonyama-zk/icicle#213]
- Define error codes for different classes of errors. 
- Make sure errors return information about the location they have been emmited from
- Create verbose error messages.

**Comment by DmytroTym** [comment]
We have some duplicates (or near-duplicates) for this one: https://github.com/ingonyama-zk/icicle/issues/109, https://github.com/ingonyama-zk/icicle/issues/38 and https://github.com/ingonyama-zk/icicle/issues/190

**Comment by vhnatyk** [comment]
Added in v1.0.0
