### ISSUE TITLE
Allow twiddle factors to be configured during run time

### ISSUE THREAD

**Issue by ImmanuelSegol** [ingonyama-zk/icicle#218]
Different applications have different configurations for twiddle factors, these can effect the output of NTT.

An example is flipping twiddles for gnark breaking this test https://github.com/ingonyama-zk/icicle/blob/fdf03460df5e5d85ade1f55a7df47ba392881281/src/test_bls12_377.rs#L1585

**Comment by DmytroTym** [comment]
Same as https://github.com/ingonyama-zk/icicle/issues/183
