### ISSUE TITLE
Fix fn test_point_batch_evaluation_on_coset test

### ISSUE THREAD

**Issue by ImmanuelSegol** [ingonyama-zk/icicle#219]
Fix this test https://github.com/ingonyama-zk/icicle/blob/fdf03460df5e5d85ade1f55a7df47ba392881281/src/test_bls12_377.rs#L1585

related to [#218](https://github.com/ingonyama-zk/icicle/issues/218)

**Comment by DmytroTym** [comment]
While technically the test is no longer there, seems like the underlying issue is solved, reopen if I'm wrong
