### ISSUE TITLE
[request for assist]:  what is the gpu arc required

### ISSUE THREAD

**Issue by cliff0412** [ingonyama-zk/icicle#226]
currently, i am using gpu arch compute_89. however it throws below error during build
```
 nvcc fatal   : Unsupported gpu architecture 'compute_89'
```

my cmake version is 3.27.6
cuda toolkit version is 

Cuda compilation tools, release 11.7, V11.7.99
Build cuda_11.7.r11.7/compiler.31442593_0

**Comment by ImmanuelSegol** [comment]
Hey @cliff0412,

We support CUDA Toolkit version 12.0 or newer. 

https://github.com/ingonyama-zk/icicle/tree/main/icicle#readme

**Comment by cliff0412** [comment]
it compiles successfully after upgrade to v12.

**Comment by ImmanuelSegol** [comment]
> it compiles successfully after upgrade to v12.

Great to hear! Thanks for helping us improve the documentation.
