### ISSUE TITLE
[FEAT]: write test that cover `large_bucket_factor`

### ISSUE THREAD

**Issue by ImmanuelSegol** [ingonyama-zk/icicle#236]
## Description

Write test that cover some options for `large_msm` param `large_bucket_factor`. Include edge cases such as in issue #231.

## Motivation

Issue #231 has shown that some pretty nasty bugs may occur in `large_msm`.

**Comment by DmytroTym** [comment]
[`check_msm_skewed_distributions`](https://github.com/ingonyama-zk/icicle/blob/main/wrappers/rust/icicle-core/src/msm/tests.rs#L152) checks different scalar distributions: scalars that are only zeroes and ones in random order, also scalars some of which are random and the rest and zeroes and ones. They should cover `large_bucket_factor` bugs that we used to have before
