### ISSUE TITLE
[FEAT]: Utilize glv decomposition to speed up MSM operations

### ISSUE THREAD

**Issue by PatStiles** [ingonyama-zk/icicle#260]
## Description

Utilizing glv decomposition to decompose scalars into two scalars of half bit length has been shown to significantly improve MSM performance for curves with an efficiently computable endomorphism. Since Icicle supports curves such as BLS12-381 which have efficiently computable endomorphisms I am curious if these savings would translate well on gpu.

Ref:
- Paper: https://www.iacr.org/archive/crypto2001/21390189.pdf
- THE OG THREAD: https://github.com/privacy-scaling-explorations/halo2/issues/187
- https://github.com/arkworks-rs/algebra/issues/59
- https://github.com/arkworks-rs/snark/pull/296
- https://hackmd.io/@aztec-network/rJ3VZcyZ9
- https://github.com/privacy-scaling-explorations/halo2curves/pull/24
- https://github.com/privacy-scaling-explorations/halo2/pull/40
- https://github.com/demining/Endomorphism-Secp256k1/blob/main/README.md

**Comment by DmytroTym** [comment]
Thanks for the suggestion. We have a number of MSM optimisations in the pipeline and haven't really tried GLV yet. GPU codebases I know of don't really have it and I think Niall Emmart says that he wasn't able to speed up MSM with cube root endomorphism at some point in [this](https://www.youtube.com/watch?v=KAWlySN7Hm8) talk (couldn't find the exact timestamp). But we do have -1 endomorphism improvement in progress.
