### ISSUE TITLE
[FEAT]: NTT acceleration

### ISSUE THREAD

**Issue by Iridescent-gcrace** [ingonyama-zk/icicle#264]
## Description
While reading this paper [GZKP](https://dl.acm.org/doi/10.1145/3575693.3575711), I found that the execution speed of NTT is faster than icicle. Are you guys interested in implementing it into icicle?

Looking forward to hearing your thoughts on this proposal. Thank you for your continuous efforts in improving Icicle.

**Comment by Iridescent-gcrace** [comment]
Thank you for your answer! Your guys' work is excellent! May I ask when the accele

**Comment by HadarIngonyama** [comment]
Hopefully in about 3 months.

**Comment by cliff0412** [comment]
i dont have the account to download the paper. what optimisation do they conduct to improve NTT?

**Comment by HadarIngonyama** [comment]
They make good use of shared memory in all the NTT stages and they have a good memory access pattern to global memory.
Our new implementation isn't based on this article, it's out own design, and it achieves even better results. Our main improvements are:
- Coalesced access to global memory
- Using shared memory for all the stages
- Fully utilizing register memory
- implementing the Winograd-8 algorithm

**Comment by cliff0412** [comment]
> They make good use of shared memory in all the NTT stages and they have a good memory access pattern to global memory. Our new implementation isn't based on this article, it's out own design, and it achieves even better results. Our main improvements are:
> 
> * Coalesced access to global memory
> * Using shared memory for all the stages
> * Fully utilizing register memory
> * implementing the Winograd-8 algorithm

when will the new implementation be out? i think currently the shared memory is only used in certain stages.

**Comment by HadarIngonyama** [comment]
The new implementation was released in release 1.3.0, it's called mixed-radix NTT. check it out - https://github.com/ingonyama-zk/icicle/blob/fc6badcb354dca03cac8e025b785d9d00b0942b8/icicle/appUtils/ntt/kernel_ntt.cu#L641

column-wise arranged inputs - I don't think this is currently supported. could you give an example for a use case? usually the NTT input is just a 1-D array, you want support for a column-wise 2-D array? I guess in that case it would depend on the column size.

**Comment by cliff0412** [comment]
> The new implementation was released in release 1.3.0, it's called mixed-radix NTT. check it out -
> 
> https://github.com/ingonyama-zk/icicle/blob/fc6badcb354dca03cac8e025b785d9d00b0942b8/icicle/appUtils/ntt/kernel_ntt.cu#L641
> 
> column-wise arranged inputs - I don't think this is currently supported. could you give an example for a use case? usually the NTT input is just a 1-D array, you want support for a column-wise 2-D array? I guess in that case it would depend on the column size.

it's just related to my specific prover. i need to implement a matrix transpose kernel and invoke the batched_ntt methods. matrix transpose takes time though. just wondering if the NTT kernel could be customized for working with both row-wise or col-wise input array. i feel it's possible, just the butterfly offset needs to be changed. In such a way, the matrix transpose is removed. however, it makes shared memory more challenging

**Comment by HadarIngonyama** [comment]
Oh I see you were talking about batched NTT. Yes, it's not currently supported but if you want I will add this functionality - there will be an option to perform the NTT on columns instead of rows, but notice that the results will also be in column ordering. If you want also a transpose to rows - you can add it to the reordering kernel. btw - what size of NTT and batch is relevant for your case?

**Comment by cliff0412** [comment]
> Oh I see you were talking about batched NTT. Yes, it's not currently supported but if you want I will add this functionality - there will be an option to perform the NTT on columns instead of rows, but notice that the results will also be in column ordering. If you want also a transpose to rows - you can add it to the reordering kernel. btw - what size of NTT and batch is relevant for your case?

thanks for your reply. it would be great if the batched ntt could support col-wised inputs. my size of NTT is around 150 rows. Each row is of length 1<< 19. the output is in col-wise is fine, As the stage after NTT is merkle tree building (col-wise is better actually).
