### ISSUE TITLE
[FEAT]: Unify building system

### ISSUE THREAD

**Issue by vhnatyk** [ingonyama-zk/icicle#265]
## Description

switch all building systems to CMake - for this we just need Golang wrapper to replace make

## Motivation

Since #244 we are ready to unify our build system to CMake

benefits of CMake are more obvious now
* Native CUDA support
     *    built-in separable compilation support
* Google Test support
* Cross-platform - Unix and Windows

**Comment by jeremyfelder** [comment]
>for this we just need Golang wrapper to replace make

The following is needed to use statically linked libs with CGO
1. Replace current cgo LDFLAGS directives to link to `-l<static_lib>`
2. Add `-lstdc++ -lm` to LDFLAGS to make cgo compile with g++ and link std libs
3. Update docs to ensure cmake is compiled with G2_DEFINED (OR make G2 inclusion optional in golang wrapper)
