### ISSUE TITLE
[ISSUE]: CMake Build Failing

### ISSUE THREAD

**Issue by bigsky77** [ingonyama-zk/icicle#268]
## Description

I'm getting a "parameter packs not expanded" error compiling Icicle using CMake.

### Reproduce

1) Clone Directory
2) `cd icicle/icicle`
3) `mkdir -p build; cmake -S . -B build; cmake --build build; cd build && ctest; cd ..`

Compilation fails during `cmake --build build` .

## Environment

Please complete the following information:

OS + Version:
Ubuntu 22.04

Cargo Version:
1.66.1

GPU type:
TU117M [GeForce GTX 1650 Ti Mobile

## Additional context

Screenshot included for context.

![Screenshot from 2023-11-20 13-09-27](https://github.com/ingonyama-zk/icicle/assets/77446076/313a61cf-a9fc-419c-82ac-39bd474c90d6)

**Comment by jeremyfelder** [comment]
@bigsky77 What cmake and c++ versions are you using?

**Comment by bigsky77** [comment]
I am using cmake 3.22.1 and c++ is (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0

**Comment by vhnatyk** [comment]
hi - what is Cuda version you are compiling with? We had exactly the same error on one system when compiling for Fast danksharding. Unfortunately, I don't remember the exact fix - will try to find out, but I recall it was two-step - one was making it compile with the correct nvcc version. Another was the correct С compiler version - in paticular gcc or g++ or both (9.4+ or newer?)

**Comment by bigsky77** [comment]
Issue resolved.

**Summary:**
- **Problem**: Oversight in CMakeLists file caused CMake build failure due to incorrect CUDA compiler path.
- **Resolution**: Correction of CUDA compiler path in CMakeLists file has resolved the issue.

**Changes Made:**
```diff
- set(CMAKE_CUDA_COMPILER /usr/local/cuda-12/nvvm/bin)
+ set(CMAKE_CUDA_COMPILER /usr/local/cuda-12/bin/nvcc)
```

The aforementioned change updates CMake with the correct CUDA compiler location, rectifying the build failure.
