### ISSUE TITLE
[BUG]:  Make build fail in goicicle

### ISSUE THREAD

**Issue by bigsky77** [ingonyama-zk/icicle#302]
## Description

When attempting to compile the CUDA code within goicicle using `make all`, the process fails with the following error:

```
/usr/local/cuda/bin/nvcc -DG2_DEFINED -Xcompiler -fPIC -std=c++17 -shared ../icicle/curves/bn254/lde.cu ../icicle/curves/bn254/msm.cu ../icicle/curves/bn254/projective.cu ../icicle/curves/bn254/ve_mod_mult.cu -o libbn254.so
gcc: error: ../icicle/curves/bn254/lde.cu: No such file or directory
gcc: fatal error: no input files
compilation terminated.
make: *** [Makefile:22: libbn254.so] Error 1
```

### Cause 

The error message indicates that the required bn254 curve files (lde.cu, msm.cu, projective.cu, ve_mod_mult.cu) are not found in the expected directory (../icicle/curves/bn254/).

### Context 

Caused by latest updates to Icicle.  Bindings compile fine on commit **f8610dd5**.

**Comment by ImmanuelSegol** [comment]
@bigsky77 having a look at this

**Comment by Otsar-Raikou** [comment]
Known issue, use V0.1.0
