### ISSUE TITLE
How to use the Rust bindings?

### ISSUE THREAD

**Issue by sss1h** [ingonyama-zk/icicle#309]
The [build script](https://github.com/ingonyama-zk/icicle/blob/main/build.rs) is gone. Does the README need to be modified?

**Comment by jeremyfelder** [comment]
@sss1h The latest `main` is considered unstable right now and we are in the middle of updating our docs. You can build bn254 using the [its crate](https://github.com/ingonyama-zk/icicle/tree/main/wrappers/rust/icicle-curves/icicle-bn254) under `wrappers/rust/icicle-curves`. More curves are on the way 😃 

For a stable API, I suggest using the tag v0.1.0

**Comment by sss1h** [comment]
Thanks a lot.
