### ISSUE TITLE
[FEAT]: Fix rust curve generation

### ISSUE THREAD

**Issue by ImmanuelSegol** [ingonyama-zk/icicle#310]
The current [script](https://github.com/ingonyama-zk/icicle/blob/main/curve_parameters/new_curve_script.py) wont work any more.

We need to update the templates.

**Comment by DmytroTym** [comment]
I wouldn't update the script, I don't think it's reasonable to expect a script to fully generate a new curve. It's still helpful to be able to auto-generate some values, and decompose numbers into limbs. But I feel like this might be best served by C++ macros, wdyt @ImmanuelSegol ?
