### ISSUE TITLE
[FEAT]: Update Supporting Additional Curves documentation

### ISSUE THREAD

**Issue by ImmanuelSegol** [ingonyama-zk/icicle#313]
## Description

Once #310 if fixed update the readme regarding generating support for new curves.

**Comment by DmytroTym** [comment]
Related to https://github.com/ingonyama-zk/icicle/issues/310

**Comment by DmytroTym** [comment]
@ChickenLover did a really good job with this in https://github.com/ingonyama-zk/icicle/pull/415, the issue can probably be closed once the PR is merged.
