### ISSUE TITLE
Rust compilation time

### ISSUE THREAD

**Issue by sss1h** [ingonyama-zk/icicle#316]
### Discussed in https://github.com/ingonyama-zk/icicle/discussions/314

<div type='discussions-op-text'>

<sup>Originally posted by **sss1h** December 20, 2023</sup>
The Rust compilation time is about 15 minutes after changing the C++ functions.  Is there any way to speed up?</div>

**Comment by jeremyfelder** [comment]
@sss1h I assume you are using v0.1.0?  What curves are you working with?
You can remove some curves from being compiled if you're not using them by removing theirs files from the list added to the library: https://github.com/ingonyama-zk/icicle/blob/v0.1.0/icicle/CMakeLists.txt#L65-L79

**Comment by vhnatyk** [comment]
fyi - after https://github.com/ingonyama-zk/icicle/pull/244 - only initial compilation indeed is expected to take quite a bit of time. Subsequent changes are expected to depend on particular files edited - if the core templates/primitives like `field.cuh` that are imported/defined in all top-files, then it can also take a bit of a time again. But we are working on sort of **development mode** - that will trade some performance for speed of compilation by avoiding unrolling etc. Then release mode can be used for final deployment and full performance. Anyway - as of [current main](https://github.com/ingonyama-zk/icicle/commit/dcaa0b4513f773da995073910f98816622ae104c) - it is expected to compile for few minutes(1-3 per curve) on a mid range laptop

**Comment by sss1h** [comment]
@jeremyfelder @vhnatyk Thanks. I am indeed using v0.1.0. I am working with BN254, so I remove bls12_377 and bls12_381 from the list.
After I edit the file `icicle/appUtils/ntt/ntt.cuh`, the compilation time is 8m 29s.
Is the reason why the compiling takes a bit of time that the `ntt.cuh` is imported/defined in all top-files?

**Comment by vhnatyk** [comment]
hi - if you work with commit after #244 [7baea7cc](https://github.com/ingonyama-zk/icicle/commit/7baea7cc5a7b756c99e29d7b3cb25c08f44ccc6f) - then 8 minutes is a bit long for subsequent compilation still, anyway ntt.cuh is indeed sort of midtier :) - template file affecting all other files importing it - so yes. Depending on the machine you use, it can be considered normal. I know  8 minutes it is still a lot but we are working on improving the initial compilation.

**Comment by vhnatyk** [comment]
uh oh - hoped in v1.0.0 we will address this as a side task, but I'm still not able to build in debug in some meaningful time and total RAM 😒 despite spending a few good hours on that over last week:) Tried all the options with unrolling an ptxas flags and optimizations disabled - debug is quite useful for, well, debugging 😄. Maybe release with `-lineinfo` and `-O0` can serve the purpose for now, especially since we added error tracking with function name(so if some line numbers are misleading - still can give approx idea about the line causing issue)
