### ISSUE TITLE
MSM benchmarking inquiry

### ISSUE THREAD

**Issue by TalDerei** [ingonyama-zk/icicle#32]
Can someone benchmark the MSM on 2^26 scalars and points, and share their results? I'm getting some mixed numbers. 

Have you tested how the bucket method implementation compares against the ZPrize reference implementation in terms of execution time / memory utilization?

@HadarIngonyama 
@LeonHibnik
@vhnatyk

**Comment by TalDerei** [comment]
Any updates on this? I saw there's a few other issues opened around MSM kernel optimizations.

**Comment by TalDerei** [comment]
Awesome work! What's the most recent branch to benchmark this MSM performance. I'd like to run some benchmarks on A10/A40. Thanks :)

**Comment by TalDerei** [comment]
Interested to benchmark the performance on A10/A40!

**Comment by HadarIngonyama** [comment]
Great! go for it and please share your results:) This was just merge to dev a few hours ago

**Comment by TalDerei** [comment]
The build failing on dev branch when trying to run `cargo build --release`

**Comment by omershlo** [comment]
thanks, checking 
cc: @vhnatyk

**Comment by vhnatyk** [comment]
Looks like BLS12-377 and BLS12-381 curves compilation slightly broken in `large_msm` method - params were not updated - we were focused on BN254 for Gnark in `dev` branch lately. Fixing

**Comment by vhnatyk** [comment]
@TalDerei hotfix is at #131 - this will be fixed upon merge to main
