### ISSUE TITLE
[FEAT]: msm on bn254 extension field is not supported

### ISSUE THREAD

**Issue by cliff0412** [ingonyama-zk/icicle#336]
## Description

I was trying to run msm over bn254 extension field, as the groth16 proof contains one msm over G2 curve. however, i got below error 
` class "ExtensionField<bn254::fq_config>" has no member "ToMontgomery"`
will msm on bn254 extension field be supported?

However, i looked into goicicle directory and noticed that there is a test named `TestMsmG2BN254`. is this historically supported but removed?

**Comment by DmytroTym** [comment]
Hi @cliff0412. Which version are you using?

**Comment by cliff0412** [comment]
i referred to v1.0.0; actually, i find out that G2 MSM is supported in v0.1.0. suggest also add it into the test

**Comment by ImmanuelSegol** [comment]
resolved by #341
