### ISSUE TITLE
[BUG]: Broken link in the documentation

### ISSUE THREAD

**Issue by AviadDahan** [ingonyama-zk/icicle#347]
## Description

in the inroduction part, under 'ICICLE CORE' 
(https://dev.ingonyama.com/icicle/introduction) 
there is a link for an example that seems to be broken.
The link: https://github.com/ingonyama-zk/icicle/blob/main/icicle/curves/bn254/msm.cu

**Comment by LeonHibnik** [comment]
@ImmanuelSegol

**Comment by Otsar-Raikou** [comment]
On it

**Comment by ImmanuelSegol** [comment]
fixed https://github.com/ingonyama-zk/developer-docs/pull/35
