### ISSUE TITLE
[BUG]: c++ ntt example throw memory error in copy from device to host

### ISSUE THREAD

**Issue by cliff0412** [ingonyama-zk/icicle#349]
## Description

I am testing ntt under `examples/c++/ntt`. the code seems outdated (not working with current cuda library, not using the latest NTTConfig), and i tried to fixed it and put the code here https://github.com/cliff0412/icicle/commit/65955bd17a1d25c4ef3432acda5ce8cde14bc5c9. the ntt invokation throw below errror
<img width="1119" alt="Screenshot 2024-01-25 at 8 02 14 PM" src="https://github.com/ingonyama-zk/icicle/assets/13556363/bad9b744-9c59-4bac-84c3-cb51985ab3e5">

the ntt kernel completes; the error occurs while copy from device to host
### Reproduce

```
cd examples/c++/ntt
mkdir build && cd build
cmake .. 
make
./example
```

**Comment by jeremyfelder** [comment]
@cliff0412 Thanks for reporting this! We will take a look at that
@svpolonsky fyi

**Comment by cliff0412** [comment]
the errror is actually `invalid device function` could this be nvcc version or gpu compute arch problem?

**Comment by jeremyfelder** [comment]
@cliff0412 The c++ NTT example should be up to date on `dev`. We should be releasing it soon.
I tested with the same cuda version, cmake version = 3.24.2 and gcc 10.5.0
