### ISSUE TITLE
[FEAT]: goldilocks poseidon hash for BN254

### ISSUE THREAD

**Issue by cliff0412** [ingonyama-zk/icicle#390]
## Description

plonky2's Goldilocks filed is the most efficient field in ZKP system ( by far as i know). to make plonky2 verifiable on chain, the poseidon hash has to be implemented for BN254. a cpu implementation is here https://github.com/iden3/go-iden3-crypto/blob/master/poseidon/poseidon.go. possible to port that into icicle also?

**Comment by LeonHibnik** [comment]
Thank you for the suggestion!

We actually have goldilocks support in our upcoming roadmap, so stay tuned

**Comment by cliff0412** [comment]
thanks for your reply. however, i am not requesting for goldilocks support, rather it is poseidon implementation over foreign BN128 field on native Goldilocks field. Currently, ethereum only has precompile for BN128 and no Goldilocks field. To make my proof verifiable on chain, i need to implement BN128 on Goldilocks of plonky2

**Comment by ChickenLover** [comment]
@cliff0412 not exactly sure what you meant, but here are three facts that might help:

1. BN128 ==BN254 (afaik). We have poseidon implemented for bn254
2. We are planning to add support for goldilocks poseidon in the future.
3. ICICLE is a general-purpose library, so unfortunately we are not planning to implement very specific cases

Closing the issue for now. Feel free to re-open or reach out in our Discord if you have any questions
