### ISSUE TITLE
[BUG]:  integrating icicle into other projects  and execute msm with wrong result. 

### ISSUE THREAD

**Issue by JimmyHongjichuan** [ingonyama-zk/icicle#458]
## Description

when integrating  icicle repo into other projects and the project has a log2 implementation. Makefile may link to the log2 implementation of the other project for the log2  which be used by icicle msm.cu file.  This may cause the result of log2 is the floor value and the result of MSM is wrong, So need to  use the log2 in lib std explicitly.

### Reproduce

Please list the steps to reproduce the issue.

## Expected Behavior

Please provide a clear and concise description of what you expected to happen.

## Environment

Please complete the following information:

OS + Version:

Cargo Version:

GPU type:

## Additional context

Please provide any additional context that may be helpful in confirming and resolving this issue.

**Comment by jeremyfelder** [comment]
Fixed in commit https://github.com/ingonyama-zk/icicle/commit/95ab6de059b11f4646ce4cf8a98dc31251b60f7f
