### ISSUE TITLE
MSM bucket segmentation 

### ISSUE THREAD

**Issue by TalDerei** [ingonyama-zk/icicle#53]
Improvement from PipeMSM paper to implement a segmented version of the buckets described in Algorithm 2. This is related to the **big_triangle_sum_kernel** kernel.

**Comment by HadarIngonyama** [comment]
This Algorithm is designed to work well on an FPGA but not on a GPU. The GPU MSM now has a very fast reduction algorithm for summing the accumulated buckets.
