### ISSUE TITLE
[FEAT]: Need an example to batch hash bytes arrays of different lengths

### ISSUE THREAD

**Issue by flyq** [ingonyama-zk/icicle#657]
## Description

I find hash field elements in batch in [this example](https://github.com/ingonyama-zk/icicle/blob/main/examples/rust/hash-and-merkle/src/main.rs), but it seems to assume that the input data has the same length (all elements). If I want to batch calculate the hash of some bytes, and these bytes have 4 types of lengths, can icicle provide this function?

btw, I see the code in merkle example:

```rust
    // Zero-padding policy is applied to ensure that input matches the expected size.
    let mut config = MerkleTreeConfig::default();
    config.padding_policy = PaddingPolicy::ZeroPadding; // Zero-padding if input is too small.
                                                        // TODO: Padding not supported in v3.1; will be available in v3.2.
```

## Motivation

Expand the application scenarios of icicle

## (optional) CUDA backend branch
cuda-backend-branch: main

**Comment by ShaniBabayoff** [comment]
thanks!
@flyq 
could you please tell me more about your case?
