### ISSUE TITLE
[FEAT]: NUM_THREADS causes slow performance？？？

### ISSUE THREAD

**Issue by WangYaoABC** [ingonyama-zk/icicle#69]
I'm curious about the change of NUM_THREADS.
It seems to cause slow performance.

  //split scalars into digits
  NUM_THREADS = **1 << 10;**
  NUM_BLOCKS = (size * (nof_bms+1) + NUM_THREADS - 1) / NUM_THREADS;
  split_scalars_kernel<<<NUM_BLOCKS, NUM_THREADS>>>(bucket_indices + size, point_indices + size, scalars, size, msm_log_size, nof_bms, bm_bitsize, c); //+size - leaving the first bm free for the out of place sort later

//launch the accumulation kernel with maximum threads
  NUM_THREADS = **1 << 8;**
  NUM_BLOCKS = (nof_buckets + NUM_THREADS - 1) / NUM_THREADS;
  accumulate_buckets_kernel<<<NUM_BLOCKS, NUM_THREADS>>>(buckets, bucket_offsets, bucket_sizes, single_bucket_indices, point_indices, points, nof_buckets, 1, c+bm_bitsize);

**Comment by LeonHibnik** [comment]
Thank you @WangYaoABC, we will look into it

**Comment by HadarIngonyama** [comment]
Could you please elaborate? what msm size did you try? and how much is the difference in performance when you increase the number of threads?

Anyway, currently there are bugs in the msm for a size greater than 2^14 which we are planning to fix in the next 2 weeks.

**Comment by WangYaoABC** [comment]
Ah,  when it was changed to 10，it will go wrong. The msm size is 2^14, and batch is 4.

I think we should check the tid at first in the function "accumulate_buckets_kernel" .

if (tid >= total_nof_buckets_to_compute )  then return;

**Comment by DmytroTym** [comment]
I feel like we solved it back then and forgot to close the issue @HadarIngonyama ?

**Comment by HadarIngonyama** [comment]
Yes, seems so, although the number of threads is still quite arbitrary, but I don't think it affects the performance.
