### ISSUE TITLE
updating rust interface to support curve operations

### ISSUE THREAD

**Issue by LeonHibnik** [ingonyama-zk/icicle#85]

**Comment by Otsar-Raikou** [comment]
[Change] Assign to Dima or Jeremy

**Comment by DmytroTym** [comment]
Not sure what's meant by curve operations exactly but:

- check for point equality is supported
- moving between affine and projective is supported
- nothing else is supported: point addition, single-scalar multiplication, pairings, is_on_curve check etc. I don't think we needed any of these so far
